simulation:
    shared:
        n_sim: 1
        duration_hours: 24
        exit_rate: 0.5
        frustration_fn: quad
        verbose: False
        save_hist: True
        lanes_config:
            -
                morning_peak_rate: 10
                evening_peak_rate: 30
            -
                morning_peak_rate: 15
                evening_peak_rate: 15
            -
                morning_peak_rate: 30
                evening_peak_rate: 10
    models:
        Baseline_40s:
            controller: ConstantController
            wait_time: 40

        Baseline_20s:
            controller: ConstantController
            wait_time: 20

        Baseline_10s:
            controller: ConstantController
            wait_time: 10

        Baseline_5s:
            controller: ConstantController
            wait_time: 5

        Idle_20s_5s:
            controller: IdleController
            wait_time: 20
            idle_time: 5

        Idle_10s_5s:
            controller: IdleController
            wait_time: 10
            idle_time: 5
