simulation:
    shared:
        n_sim: 1
        duration_hours: 1
        exit_rate: 0.5
        frustration_fn: quad
        verbose: False
        save_hist: True
        lanes_config:
            -
                morning_peak_rate: 20
                evening_peak_rate: 30
            -
                morning_peak_rate: 20
                evening_peak_rate: 20
            -
                morning_peak_rate: 30
                evening_peak_rate: 20
    models:
        Baseline_20:
            controller: ConstantController
            wait_time: 20

        Baseline_40:
            controller: ConstantController
            wait_time: 40

#        Idle_20_5:
#            controller: IdleController
#            wait_time: 20
#            idle_time: 5
#
#        Idle_40_5:
#            controller: IdleController
#            wait_time: 40
#            idle_time: 5
