simulation:
    shared:
        n_sim: 1
        duration_hours: 24
        exit_rate: 0.5
        frustration_fn: quad
        verbose: False
        save_hist: True
        lanes_config:
            -
                morning_peak_rate: 10
                evening_peak_rate: 30
            -
                morning_peak_rate: 15
                evening_peak_rate: 15
            -
                morning_peak_rate: 30
                evening_peak_rate: 10
    models:
        Baseline_20:
            controller: ConstantController
            wait_time: 20

        Baseline_10:
            controller: ConstantController
            wait_time: 10

        Baseline_5:
            controller: ConstantController
            wait_time: 5

        Idle_20_5:
            controller: IdleController
            wait_time: 20
            idle_time: 5

        Idle_10_5:
            controller: IdleController
            wait_time: 40
            idle_time: 5
