simulation:
    shared:
        n_sim: 1
        duration_hours: 24
        exit_rate: 1
        frustration_fn: quad
        verbose: False
        save_hist: True
        lanes_config:
            -
                morning_peak_rate: 10
                evening_peak_rate: 20
            -
                morning_peak_rate: 15
                evening_peak_rate: 15
            -
                morning_peak_rate: 20
                evening_peak_rate: 10
    models:

        Baseline_20s:
            controller: ConstantController
            wait_time: 20

        Idle_10s_5s:
            controller: IdleController
            wait_time: 20
            idle_time: 5

        snapshot_controller:
            controller: SnapshotController
            rate_lookback: 300
            loop_duration: 60